### ISSUE TITLE
I have macbook m3 max 48 gb, can it ran on Macos?

### ISSUE THREAD

**Issue by shadowzoom** [instantX-research/InstantIR#10]
I have macbook m3 max 48 gb, can it ran on Macos?

**Comment by JY-Joy** [comment]
Unfortunately we do not have such a device for testing :( FYI we have found users trying InstantIR on apple silicon devices and they report the performance in this [twi](https://x.com/cocktailpeanut/status/1854956231544520728). We will try to test it on similar platform recently, so if you encounter any error please start a new issue and we will take care.
