### ISSUE TITLE
Requirements.txt not found

### ISSUE THREAD

**Issue by KhanShahswar** [instantX-research/InstantIR#11]
Encountered following error while installing InstantIR:

(instantir) ha****al@DESKTOP-*****BT:/mnt/c/InstantIR/InstantIR$ pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Encountering this error both on Win10X64 and WSL2

**Comment by KhanShahswar** [comment]
Hi Joy! Thankyou for prompt reply You are right that there is a duplicate "InstantIR" folder however at root of cloned git repo still many files are missing. Please check Dir structure in attached Dir.txt file.   
[Dir.txt](https://github.com/user-attachments/files/17698335/Dir.txt)

I think due to some odd reason "git clone https://github.com/JY-Joy/InstantIR.git" isn't working as intended.

**Comment by JY-Joy** [comment]
Hi Khan, now I see the problem. We've transferred the repo from 'JY-Joy' to InstantX official account. That means you have to use `git clone https://github.com/instantX-research/InstantIR.git` to get our latest code. I'm really sorry for the confusion, I've changed JY-Joy/InstantIR to private repo to avoid things like that.

**Comment by KhanShahswar** [comment]
Ahh.... got it! thanks! It happens, no worries. Stay blessed

**Comment by JY-Joy** [comment]
Enjoy your time with InstantIR! If u have other problems please start a new issue and we'll take care!
