### ISSUE TITLE
A tensor mismatch error occurred in the middle of the build

### ISSUE THREAD

**Issue by Mingsirdon** [instantX-research/InstantIR#3]
On the first boot after deployment, an error shows that the adapter named "default" could not be found, and the currently loaded adapter only has "previewer" and "lcm".
I successfully entered the gradio interface after modifying the code "default" to "previewer", but there was an error in the middle of processing, prompting me that the tensors did not match, what is the reason for this, I hope to get an answer, and I also want to tell you what kind of machine configuration is needed to run locally, thank you very much.

The same error is with the file deployment in the repository I was using at the beginning, and the same error is with the file deployment I cloned on Huggingface.
The following is my console log information, python 3.9 version is the same error.
E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
Loading SDXL...
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [05:47<00:00, 49.61s/it]
Loading LQ-Adapter...
E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
use lora alpha 1
use lora alpha 8.0
The config attributes {'interpolation_type': 'linear', 'skip_prk_steps': True, 'use_karras_sigmas': False} were passed to LCMSingleStepScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
The config attributes {'interpolation_type': 'linear', 'skip_prk_steps': True, 'use_karras_sigmas': False} were passed to LCMSingleStepScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
Loading checkpoint...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
init latent at 958
  0%|                                                                                           | 0/30 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AIGAME\InstantIR\app.py", line 135, in instantir_restore
    out = pipe(
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AIGAME\InstantIR\pipelines\sdxl_instantir.py", line 1517, in __call__
    cross_attention_emb = self.unet.time_embedding(cross_attention_t_emb, timestep_cond)
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\diffusers\models\embeddings.py", line 345, in forward
    sample = self.linear_1(sample)
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AIGAME\InstantIR\py310_cuda118\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype

**Comment by JY-Joy** [comment]
Hello Minsirdon, thanks for your feedback to our gradio script. The first lora naming problem is fixed in the latest commit. As for the second error, it seems like a mismatch of data type happens, but unfortunately I haven't encounter it on my local machine. I will try other testing environment and see if I can reproduce it, but it will be helpful if you can provide another feedback of our latest commit.
Thanks for using InstantIR!

**Comment by fallbernana123456** [comment]
> time_embedding

the same error.  
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half

**Comment by zhenbuxianggaimingzi** [comment]
same error...
```
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half
```

and here is my instruct: 
```
python infer.py --sdxl_path stable-diffusion-xl-base-1.0/ --vision_encoder_path dinov2-large/ --instantir_path InstantIR/models/ --test_path ./test/ --out_path ./results/ --num_inference_steps 50 --cfg 9.0 --height 1024 --preview_start 0.5
```

**Comment by JY-Joy** [comment]
Thanks for your feedback @zhenbuxianggaimingzi . In your comment
> same error...
> 
> ```
> RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half
> ```
do you encounter the same error where @Mingsirdon posted? or u can just paste full traceback error here and I'll check.

**Comment by yikexiaoxing** [comment]
RuntimeError: mat1 and mat2 must have the same dtype

**Comment by zhenbuxianggaimingzi** [comment]
Yes, the error traceback is the same,  it breaks in this line:  https://github.com/instantX-research/InstantIR/blob/9aaf9e7564062ad155d3d15befb85f5d8b67ae32/pipelines/sdxl_instantir.py#L1517
and here is my traceback:
![image](https://github.com/user-attachments/assets/af218b8b-bed7-48d6-bedc-b3a82c620b8c)

**Comment by fefespn** [comment]
you can set
pipe.vae.config.force_upcast = False and problem solve

the problem occure in pipe forward in :
if image.shape[1] != 4:
            needs_upcasting = self.vae.dtype == torch.float16 and self.vae.config.force_upcast
            if needs_upcasting:
                image = image.float()

**Comment by JY-Joy** [comment]
Thanks @fefespn ! We’ve forced to cast ‘image’ to fp16 to avoid the dtype mismatch in the latest commit. Please pull the latest repo @Mingsirdon @fallbernana123456 @zhenbuxianggaimingzi  @yikexiaoxing

**Comment by zhenbuxianggaimingzi** [comment]
it works~ thanks very much!

**Comment by JY-Joy** [comment]
Enjoy your time with InstantIR!

**Comment by Mingsirdon** [comment]
> 好用~非常感谢！

你好，请问你的机器是什么配置？我现在生成30步时间需要很长，你生成需要多久呢？

**Comment by Mingsirdon** [comment]
> 享受 InstantIR 的时光！

Can you tell us the recommended machine configuration for running? thank

**Comment by JY-Joy** [comment]
Hi @Mingsirdon, running InstantIR requires at least 22GB of VRAM. Besides that, latest GPU/driver will accelerate InstantIR obviously.
