### ISSUE TITLE
some code error in unet_2d_extractKV_res.py

### ISSUE THREAD

**Issue by smthemex** [instantX-research/InstantIR#5]
looks like miss:  from torch.nn import functional as F (line 115)
and line 630&653 has some "mid_block_type"

**Comment by JY-Joy** [comment]
Hi @smthemex, the module defined in `unet_2d_extractKV_res.py` is deprecated. For simplicity we've removed them in the latest commit. However, the inference and training script should run without bug. If you encountered further error, please start a new issue and we'll take care.

Thanks for all!
