### ISSUE TITLE
OK, another ,need comfirm this..

### ISSUE THREAD

**Issue by smthemex** [instantX-research/InstantIR#6]
[ get_adapter_layers](https://github.com/instantX-research/InstantIR/blob/main/module/attention.py#L41) 
Function loss

**Comment by JY-Joy** [comment]
fixed

**Comment by smthemex** [comment]
InstantIR is currently working well in my workflow,Nice work

**Comment by JY-Joy** [comment]
Good to know! Enjoy your time with InstantIR, and stay tuned as we gonna release our web demo 🚀🚀🚀
